---
title: "Inclusion Summary"
subtitle: "Training: Advocating for Educational Services"
date: "October-December 2022"

params:
  cohort: "2325Q1"

output: 
  html_document:
    df_print: paged
    fig_width: 8
---
<!-- NEEDED INFORMATION - LOOK HERE
To make this work, we need to change the names of the cohorts of the quarter to the same name.
Do this in the "r excel file" chunk (starting line 65). Change name to YYYYQN (ex. 2325Q1).
Update cohort parameter in YAML to new quarter cohort.-->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      cache = FALSE)
```

```{r library, include=FALSE}
library(tidyverse)
library(skimr)
library(janitor)
library(ggthemes)
library(hrbrthemes)
library(readxl)
library(ggtext)
library(ggalt)
library(ragg)
library(systemfonts)
library(gt)
library(knitr)
library(pagedown)
library(dplyr)
library(scales)
library(lubridate)
library(ggplot2)
```

```{r colors, include=FALSE}
psu_green <- "#6d8d24"
psu_electricgreen <- "#cfd82d"
psu_forestgreen <- "#213921"
psu_blue <- "#008ac1"
psu_lightblue <- "#a5dff9"
psu_sand <- "#e8d3a2"
psu_stone <- "#8a8a67"
psu_yellow <- "#ffc20e"
psu_red <- "#e64927"
psu_orange <- "#f68b1f"
psu_purple <- "#650360"
```

```{r excel file, include=FALSE}
aes_inclusion <- read_excel(path = "I:\\Staff\\GSSW\\SALEM\\DATA ENTRY\\2. Well-being\\AES DB 202307.xlsx",
                                   sheet = "session") %>% 
  clean_names() %>% 
  select(cohort, id_trainer, id_other, id_comment) %>% 
  mutate(cohort = as.character(cohort)) %>% 
  mutate(cohort = if_else(cohort == "202307", "2325Q1", cohort)) %>% 
  mutate(cohort = if_else(cohort == "202308", "2325Q1", cohort)) %>% 
  mutate(cohort = if_else(cohort == "202309", "2325Q1", cohort))
```

```{r number respondents, include=FALSE}
number_respondents_inclusion <- aes_inclusion %>% 
  filter(cohort == params$cohort) %>% 
  count(cohort) %>% 
  pull(n)
```

Number of Respondents in Quarter: **`r number_respondents_inclusion`**

```{r}
aes_inclusion_scales <- aes_inclusion %>%
  select(-id_comment) %>% 
  pivot_longer(cols = -cohort,
               names_to = "scale",
               values_to = "rating",
               values_drop_na = TRUE)
```

```{r trainers, fig.height = 3.5, fig.width = 7}
aes_inclusion_scales %>%
  filter(cohort == params$cohort,
         scale == "id_trainer") %>% 
  drop_na() %>% 
  count(cohort, scale, rating) %>% 
  mutate(pct = n / sum(n)) %>% 
  ggplot(aes(x = pct,
             y = rating,
             fill = rating)) +
  geom_col(show.legend = TRUE,
           position = "fill") +
  geom_text(aes(label = scales::percent(pct, accuracy = 1)),
            color = "black",
            hjust = -0.2,
            size = 3) +
  scale_x_continuous(expand = expansion(add = c(0,0.2)),
                     labels = NULL) +
  labs(title = "I felt respected based on my identities by <span style = 'color: #008ac1'>trainers/staff</span>",
       fill = "") +
  theme_minimal() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        axis.title = element_blank(),
        plot.title = element_markdown(face = "bold"))
```

scale_fill_manual(values = c(
                     "1" = psu_red,
                     "2" = psu_orange,
                     "3" = psu_yellow,
                     "4" = psu_sand,
                     "5" = psu_electricgreen,
                     "6" = psu_green,
                     "7" = psu_forestgreen)) +

